### ISSUE TITLE
@username issue

### ISSUE THREAD

**Issue by girishnayak12** [RimeOfficial/postmaster#17]
In maiI when user cIicks on user name it takes to some where  
ex. http://rime/@grum/?utm_source=Tips-9&utm_campaign=9+Welcome+To+The+World+of+Awesomeness%21&utm_medium=email&utm_content=hyperlink

**Comment by suvozit** [comment]
Yes it was a bug :( 
https://github.com/RimeOfficial/mails/commit/aeb8f0d4f7d509ed7fc3350229f390c269e7927d
